# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-14 19:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job_place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('j_place', models.CharField(max_length=32, verbose_name='Организация')),
                ('j_time', models.CharField(max_length=32, verbose_name='Время работы')),
                ('position', models.CharField(max_length=16, verbose_name='Должность')),
                ('resp', models.TextField(verbose_name='Обязанности')),
            ],
        ),
    ]
