# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-15 18:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='St_place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('st_place', models.CharField(max_length=128, verbose_name='Учебное заведение')),
                ('st_time', models.CharField(max_length=32, verbose_name='Годы обучения')),
                ('department', models.CharField(max_length=128, verbose_name='Факультет')),
                ('specialisation', models.CharField(max_length=128, verbose_name='Специальность')),
            ],
        ),
        migrations.AlterField(
            model_name='job_place',
            name='j_place',
            field=models.CharField(max_length=128, verbose_name='Организация'),
        ),
    ]
