# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-18 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20161215_2130'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Организация')),
                ('region', models.CharField(blank=True, max_length=32, verbose_name='Регион')),
                ('site', models.URLField(blank=True, verbose_name='Сайт')),
                ('phone', models.CharField(blank=True, max_length=16, verbose_name='Телефон')),
            ],
        ),
        migrations.RenameField(
            model_name='job_place',
            old_name='j_place',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='job_place',
            name='j_time',
        ),
        migrations.AddField(
            model_name='job_place',
            name='period',
            field=models.CharField(blank=True, max_length=16, verbose_name='Время работы'),
        ),
        migrations.AlterField(
            model_name='job_place',
            name='position',
            field=models.CharField(max_length=32, verbose_name='Должность'),
        ),
    ]
