# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-18 19:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20161218_2022'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Organization',
            new_name='Organisation',
        ),
    ]
