# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-19 20:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_auto_20161218_2328'),
    ]

    operations = [
        migrations.CreateModel(
            name='Com_card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('information', models.TextField(verbose_name='О компании')),
            ],
        ),
    ]
