# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-19 20:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_com_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='com_card',
            name='j_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.Organisation', verbose_name='Организация'),
        ),
    ]
